### ISSUE TITLE
Feature Request: Configuration Value for TinyTuya WebUI

### ISSUE THREAD

**Issue by Noschvie** [mschlenstedt/LoxBerry-Plugin-Tuya#2]
Please have a look to this hardcoded port number 8888. Is used by the plugin "RPi Monitor" too.

https://github.com/mschlenstedt/LoxBerry-Plugin-TinyTuya/blob/04aaf1e9116a40d91215991d225698a119ff5f61/webfrontend/htmlauth/index.cgi#LL263C53-L263C53

Thanks!

**Comment by Noschvie** [comment]
The port number 8888 is part of the "TinyTuya API Server".
[APIPORT = 8888](https://github.com/jasonacox/tinytuya/blob/db521e799a17f9d68fddecdb973a85c76716cbaf/server/server.py#L68)

Script server.py shall get this parameter, isn't it ?

**Comment by mschlenstedt** [comment]
Must be changed also in MQTT_Gateway and in Javascript of TinyTuya Server. Fixed in V1.0.0
