### ISSUE TITLE
DP Übersetzung ist kurz sichtbar und dann undefined

### ISSUE THREAD

**Issue by JanFellner** [mschlenstedt/LoxBerry-Plugin-Tuya#6]
Hallo Michael,

ich versuchs mal, hier wenn du möchtest das ich den Issue im Forum platziere mache ich hier wieder zu.
Ich bin deiner loxberry Anleitung gefolgt um (reichlich spät für dieses Jahr ;)) meine Pool Wärmepumpe dann doch endlich mal mit meiner Loxone steuern zu können.

Das funktioniert als Prototyp auch soweit, leider habe ich ein Problem mit dem Mapping der DPs in die Namen.

Ich habe auch hier die Anleitung befolgt und die entsprechende Konfiguration in der Tuya IoT Platform gemacht.

Wenn ich die Bridge neu starte sehe ich die Datenpunkte kurz, und diese sind anschließend wieder undefined.
Kannst du mich in eine passende Richtung schubsen?
- Wo finde ich Logs?
- Ich gehe mal davon aus das dies ein Issue in der Bridge ist, mit 90 offnen Tickets in der Bridge gehe ich mal davon aus das hier nicht wirklich zug drinn ist...

Danke ;)

Jan

**Comment by JanFellner** [comment]
Nach dem Neustart
![grafik](https://github.com/mschlenstedt/LoxBerry-Plugin-TinyTuya/assets/53753460/0fe48f06-6d95-4e51-bb7b-035b7dd9b9f9)

und sofort danach:
![grafik](https://github.com/mschlenstedt/LoxBerry-Plugin-TinyTuya/assets/53753460/5531af52-557f-4196-ab53-1356d0e51640)

**Comment by mschlenstedt** [comment]
Bin ich etwas überfragt - kann eigentlich nur etwas mit Javascript zu tun haben. Aber der Teil stammt aus dem TinyTuya Project, ich habe da nichts gemacht. Hast Du mal einen anderen Browser probiert? Getestet ist das Ganze mit Chrome.

Sonst mal mit F12 die Entwicklerconsole in Chrome öffnen und beobachten, ob in der Console Fehler angezeigt werden.

Von der Funktion des Plugins sollte das aber unabhängig sein - die Befehle aus LoxoneConfig heraus sollten trotzdem mit der DP Übersetzung laufen - hier ist ja nur die Visualisierung betroffen - die Übersetzungen hat er ja ganz offensichtlich.

**Comment by mschlenstedt** [comment]
Wegen Inaktivität geschlossen.
